### PR TITLE
Added default nullable filter.

### PR DESCRIPTION
**Pull request by stilbu**
Hi,

I am using this nice Xml extension on a project i am working on.
I added a default nullable filter (perhaps this can be done prettier?) to the code.

Do you mind if i contribute to this project? Great job on using c# 6 :+1:

### CODE REVIEW

**Comment by beto-rodriguez** [comment]
Thank you for helping this library. Your idea is nice. But for example in my case I prefer to return a 'false' string. Filters that this libary should include could be `lowerCase`, `uperCase`, `dateTimeShort`, `dateTimeLong`, etc... I mean things that we all could need.

Since that is a preference for your case, you should add it only to your Compiler class, as explained here https://github.com/beto-rodriguez/SuperXml#filters.

here is an example that can help you:

``` c#
Compiler.Filters["nullable"] = x =>
            {
                if(x.ToString() == false.ToString())
                      return "";
                 return x.ToString();
            });
```

Hope it helps! thank you again!

**Comment by stilbu** [comment]
But in my situation the return value of False (on every nullable field) is undesired.

Instead of making a custom filter, could i make that a config option of the Compiler? So people can toggle the behavior when handling nullable fields?

**Comment by beto-rodriguez** [comment]
I like that. What causes it is this ugly plain `false`. 

https://github.com/beto-rodriguez/SuperXml/blob/master/SuperXML/Compiler.cs#L573

I think it would be a good idea to create a dynamic property `OnNullOrNotFound`. and instead of returning that ugly `false`, return the value of that property.

I can add it later, or it would be awesome if you add it.

```
parameters.Add("p" + p, Parent.GetValueFromScope(i.Value) ?? OnNullOrNotFound); 
```

**Comment by stilbu** [comment]
Allright, i will add that tomorrow, and remove the filter. Thanks.

**Comment by stilbu** [comment]
Can you take a look at the last checkin? The option is added.

**Comment by beto-rodriguez** [comment]
I will push your suggestions on next release. thanks

**Comment by niteenb4u** [comment]
How Can I get this change? I am trying to use OnNullOrNotFound property but not getting. @beto-rodriguez have you pushed this changes in the latest release? 
Btw, superXML is very much helpful for generating a complex XML.

**Comment by stilbu** [comment]
Unfortunately he never merged this change into main.

2017-07-28 8:23 GMT+02:00 niteenb4u <notifications@github.com>:

**Comment by niteenb4u** [comment]
thanks for information @stilbu , can you please share the changes with me? I am trying same like you to give empty value in XML if attributes is passed to NULL or EMPTY.

**Comment by frankii91** [comment]
The nuget version does not contain the fixer configuration correction:
Compiler.OnNullOrNotFound = "";

Can you send it to Nuget?

**Pull request merged**
